name: ci
on: push
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ">=3.7"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install prerequisites
        run: |
          python -m pip install -q -U pip
          python -m pip install -q -r requirements-dev.txt -r requirements.txt
      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
      - name: Run tests
        run: |
          pytest
  publish:
    if: github.ref == 'refs/heads/master'
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: imperialcollegelondon/pytest_template_application/fibonacci
          tag_with_ref: true
          tag_with_sha: true
